liquibase:
  enabled: false
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: localhost
    port: 25
    test-connection: false
    username: ${gmail.username:admin}
    password: ${gmail.password:admin}
    properties:
      mail.smtp.starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: none
    
  